# Generated by Django 3.0 on 2019-12-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadVideo',
        ),
    ]
