# Generated by Django 3.0 on 2019-12-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vals', '0002_delete_downloadvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=256, upload_to='response')),
                ('filename', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
