# Generated by Django 3.0 on 2019-12-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vals', '0003_downloadvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadVideo',
        ),
    ]
