# Generated by Django 3.0 on 2020-01-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='composer.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Real_mid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_mid', models.FileField(upload_to='music_database')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='composer.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Primer_mel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_mel', models.TextField(null=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='composer.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.FileField(upload_to='music_database')),
                ('backing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='composer.Backing')),
            ],
        ),
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chord', models.CharField(max_length=128)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='composer.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Bpm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField(max_length=500)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='composer.Song')),
            ],
        ),
        migrations.AddField(
            model_name='backing',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='composer.Song'),
        ),
    ]
