# Generated by Django 3.0 on 2020-01-11 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0003_auto_20200106_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpm',
            name='song',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='song',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='backing',
        ),
        migrations.RemoveField(
            model_name='primer_mel',
            name='song',
        ),
        migrations.RemoveField(
            model_name='real_mid',
            name='song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Backing',
        ),
        migrations.DeleteModel(
            name='Bpm',
        ),
        migrations.DeleteModel(
            name='Chord',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Primer_mel',
        ),
        migrations.DeleteModel(
            name='Real_mid',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
